[package]
name = "quicksilver_derive"
version = "0.1.0"
license.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
description = "proc macro for quicksilver"

[lib]
proc-macro = true

[dependencies]
